# This is the basic workflow to build ICS documentation

name: Snapshot Build
# The VERSION is the main release number i.e. 1.7 or 2.1
env:      
  XJDF_VERSION:   '2.0'
  XJDF_FILE_NAME: ICS XJDF PrintProcurement
  CONFIG_FILE:    ICS_XJDF_PrintProcurement.ini

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

  workflow_dispatch:
    inputs:
      tags:
        description: 'Manual Run'  
    
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: [framemaker-2015]
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout source
        uses: actions/checkout@v2

      # New get date
      - name: Get current time/date
        uses: srfrnk/current-time@master
        id: current-time
        with:
          format: YYYYMMDD
          
      # Uses the remote self-host to build the ICS
      # By 'renaming' the configuration variables to local variables
      # we can always use the identical python command
      - name: Build Specification
        env:
          NOW: "${{ steps.current-time.outputs.formattedTime }}"
          version:      ${{env.XJDF_VERSION}}
          filename:     ${{env.XJDF_FILE_NAME}} 
          configfile:   ${{env.CONFIG_FILE}}
        run: >
          python Build\specbuilder.py $env:configfile
          "$env:filename $env:version DRAFT-$env:NOW Build-$env:GITHUB_RUN_NUMBER"
          "$env:version DRAFT-$env:NOW Build-$env:GITHUB_RUN_NUMBER"
          "Run-$env:GITHUB_RUN_NUMBER"

      # Upload any artefact produced.
      - name: Upload ICS Specification artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.XJDF_FILE_NAME }}-artifact
          path: target/*.pdf
          
      # Upload to Confluence
      - name: Confluence Upload
        uses: cip4/action-confluence-upload@master
        with:
          url: 'https://confluence.cip4.org'
          username: ${{ secrets.CONFLUENCE_USER }}
          password: ${{ secrets.CONFLUENCE_PASSWORD }}
          contentId: 15663320
          label: 'ics-xjdf-printprocurement,ics-draft'
          filePattern: 'target/*.pdf'
